services:
  main_app:
    build: ./main_app
    image: pix2chocolate-shop-main_app:latest
    ports:
      - "8001:8000"
  preview_maker:
    build: ./preview_maker
    image: pix2chocolate-shop-preview_maker:latest
    ports:
      - "8002:8036"
  part_maker:
    build: ./part_maker
    image: pix2chocolate-shop-part_maker:latest
    ports:
      - "8003:8037"
